name: sales_rep_app
description: A Flutter desktop application for sales representatives.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  path_provider: ^2.1.1
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
